# Site settings
title: Mohan
url: http://mohankumarrathinam.com
baseurl: ""
# the protocol and hostname of your site, eg. `http://laobubu.github.io`
# the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: Sample Applications from open source technologies 

# Your information
email: mohan.cse17@gmail.com.com
author: Mohankumar Rathinam
avatar: "/images/guy.jpg"
profile: A Java Developer
whatsapp: +91-9738831611
twitter_username: https://twitter.com/mohancse1707
github_username:  https://github.com/mohancse1707

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: mohankumarrathinam-com   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: "/:categories/:year/:month/:day/:title/"

gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
